scim:
  credentialsVolume: null
  credentialsSecret:
    name: op-scim-bridge-credentials
    key: scimsession
  service:
    enabled: true
    type: NodePort
  probes:
    liveness:
      enabled: false
  config:
    redisURL: "redis://{{ .Release.Namespace }}-redis-master:6379"
