apiVersion: v2
name: op-scim-bridge
version: 2.11.1
description: A Helm chart for deploying the 1Password SCIM bridge
keywords:
  - "1Password"
  - "1Password SCIM bridge"
  - "SCIM"
  - "automated provisioning"
  - "Azure Active Directory"
  - "JumpCloud"
  - "Okta"
  - "OneLogin"
  - "Rippling"
home: https://support.1password.com/scim
maintainers:
  - name: 1Password Provisioning Team
    email: support+scim@1password.com
icon: https://1password.com/img/logo-v1.svg
appVersion: v2.9.1
dependencies:
  - name: redis
    version: ~18
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: common
    version: ~2
    repository: https://charts.bitnami.com/bitnami
