# docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: 1Password Community
    url: https://1password.community/categories/scim-bridge
    about: Ask general SCIM bridge and automated provisioning questions here.
  - name: 1Password Support
    url: https://support.1password.com/contact/
    about: Create a support request.
  - name: 1Password Security Bug Bounty
    url: https://bugcrowd.com/agilebits
    about: Report security vulnerabilities here.
