{{- if .Values.scim.ingress.enabled -}}
{{- $name := tpl .Values.scim.name . -}}
{{- if and .Values.scim.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.scim.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.scim.annotations "kubernetes.io/ingress.class" .Values.scim.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ $name }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.scim.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.scim.ingress.className }}
  {{- end }}
  {{- with .Values.scim.ingress }}
  {{- if .tls.enabled }}
  tls:
    - hosts: 
        - {{ .domain | quote }}
      # TODO: Figure out why templating this in the values file doesn't work
      secretName: "{{ $.Chart.Name }}-bridge-tls"
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.scim.ingress.domain }}
    - host: {{ .Values.scim.ingress.domain | quote }}
      http:
        paths:
          - path: {{ .Values.scim.ingress.path }}
            {{- if and .Values.scim.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.scim.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: "{{$name}}-svc"
                port:
                  number: 80
              {{- else }}
              serviceName: "{{$name}}-svc"
              servicePort: 80
              {{- end }}
          {{- end }}
    {{ else }}
      {{- fail "A domain for the deployment must be specified. This is *not* a 1Password.com address. Example: '1password-scim-bridge.yoursite.com'" }}
{{- end }}
