{{ if .Values.scim.credentialsVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.scim.name . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ tpl .Values.scim.name . }}
    {{ with .Values.scim.labels }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ with .Values.scim.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{ if .Values.scim.storageClass }}
  storageClassName: {{ .Values.scim.storageClass }}
  {{ end }}
{{ end }}
