{{- if .Values.scim.credentialsSecret }}
{{- if or .Values.scim.credentialsSecret.value_json .Values.scim.credentialsSecret.value_base64 }}
{{- if and .Values.scim.credentialsSecret.value_json .Values.scim.credentialsSecret.value_base64 }}
  {{- fail "Only one of scim.credentialsSecret.value_json and scim.credentialsSecret.value_base64 can be specified" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.scim.credentialsSecret.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ tpl .Values.scim.name . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.scim.credentialsSecret.key }}: |-
  {{- if .Values.scim.credentialsSecret.value_json }}
  {{- .Values.scim.credentialsSecret.value_json | b64enc | indent 2 }}
  {{- else }}
  {{- .Values.scim.credentialsSecret.value_base64 | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
