{{- if .Values.scim.credentialsSecret.enabled }}
{{- if and .Values.scim.credentialsSecret.enabled .Values.scim.credentialsVolume.enabled }}
  {{- fail "Either credentialsSecret or credentialsVolume may be specified, not both"}}
{{- end }}
{{- if not .Values.scim.credentialsSecret.data }}
  {{- fail "Contents of the scimsession file must be provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.scim.credentialsSecret.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ tpl .Values.scim.name . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.scim.credentialsSecret.key }}: |-
    {{ toJson .Values.scim.credentialsSecret.data | b64enc }}
{{- end }}
