{{ if .Values.scim.credentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.scim.credentialsSecret.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ tpl .Values.scim.name . }}
    {{ with .Values.scim.labels }}
      {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ with .Values.scim.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
type: Opaque
stringData:
  {{ .Values.scim.credentialsSecret.key }}: |
    {{ .Values.scim.credentialsSecret.value }}
{{ end }}
