{{- if .Values.scim.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.scim.serviceAccount.name }}
  name: {{ .Values.scim.serviceAccount.name }}
  {{- else }}
  name: {{ tpl .Values.scim.name . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ tpl .Values.scim.name . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}