{{- if .Values.scim.credentialsVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.scim.name . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ tpl .Values.scim.name . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.scim.credentialsVolume.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.scim.credentialsVolume.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.scim.credentialsVolume.storageClass }}
  {{- if (eq "-" .Values.scim.credentialsVolume.storageClass) }}
  storageClassName: '""'
  {{- else }}
  storageClassName: "{{ .Values.scim.credentialsVolume.storageClass }}"
  {{- end }}
{{- end }}
{{- end }}
