scim:
  name: "{{ .Chart.Name }}-bridge"
  version: "{{ .Chart.AppVersion }}"
  # credentialsSecret:
  #   name: "{{ .Chart.Name }}-bridge-credentials"
  #   key: scimsession
  credentialsVolume:
    name: "{{ .Chart.Name }}-bridge-credentials"
    file: scimsession
    type: emptyDir
    values: {}
  imageRepository: 1password/scim
  httpPort: 8080
  httpsPort: 8443
  serviceType: LoadBalancer
  redisURL: "redis://{{ .Chart.Name }}-bridge-redis-master:6379"
  imagePullPolicy: Always
  storageClass: do-block-storage
  credential:
    name:
    key:
    file:
  probes:
    liveness:
      enabled: true
      path: "/ping"
  resources: {}
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}

redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: latest
    pullPolicy: IfNotPresent
  cluster:
    enabled: false
  usePassword: false
