name: Lint and test charts
on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      # Set up Python for ct lint, which needs Python for Yamale and yamllint
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up ct CLI
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: v3.4.0

      - name: Check if chart has changed
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Lint chart
        run: ct lint --config ct.yaml

      - name: Install yq
        run: sudo snap install yq
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add secrets and fixtures required by tests
        env:
          OP_SESSION: ${{ secrets.OP_SESSION }}
          OP_TOKEN: ${{ secrets.OP_TOKEN }}
        run: |
          cat > fixtures.yaml << EOF
          acceptanceTests:
            enabled: true
          EOF
          for values_file in op-scim-bridge/ci/*.yaml; do
            # Add secrets
            yq eval '.scim.credentialsSecret.value = strenv(OP_SESSION) | .scim.credentialsSecret.token.value = strenv(OP_TOKEN)' -i $values_file
            # Add acceptance test fixtures
            yq eval-all --inplace 'select(fileIndex == 0) * select(fileIndex == 1)' $values_file fixtures.yaml
          done

      - name: Spin up local Kubernetes cluster
        uses: helm/kind-action@v1.2.0

      - name: Deploy and run acceptance tests
        run: ct install --config ct.yaml
